Dev/nojoven/clear old worflfows from db
ovh/celery-director pull request #108
Opened 2021-07-28 14:02 UTC by nojoven

In __init__.py  I decided to check if the retention is positive before this code review.

2021-07-30 10:42 UTC, ncrocfer requested changes

2021-07-30 10:42 UTC, ncrocfer commented on director/__init__.py
> +    workflows_to_delete = []
This variable is not used, you can remove it.

2021-07-30 10:42 UTC, ncrocfer commented on director/__init__.py
> +from director.models.workflows import Workflow
This import is not used

2021-07-30 10:42 UTC, ncrocfer commented on docs/docs/guides/clean-workflows.md
> +You can find more details about the periodic workflows commands in [the build guide](https://ovh.github.io/celery-director/guides/build-workflows/).
Please use relative path.

2021-07-30 10:42 UTC, ncrocfer commented on docs/docs/guides/clean-workflows.md
> +For each workflow that is present in your *workflows.yml*, the cleaning process will:
Please don't explain how your code works but how the user can use this feature ^^

2021-09-03 09:40 UTC, ismailrei approved these changes

2021-09-03 11:13 UTC, maximecaruchet approved these changes

2021-09-06 16:00 UTC, ncrocfer approved these changes

2021-09-06 16:07 UTC, merged