feat: Add per-task queue routing
ovh/celery-director pull request #155
Opened 2022-06-30 13:30 UTC by henri42

Add the possibility to route task individually in a workflow.

```yaml
example.ETL:
  tasks:
    - [EXTRACT, queue1]
    - [TRANSFORM, queue2]
    - LOAD
```

In the following case, the task-level queue overrides the workflow-level queue for the task where a queue is defined.
```yaml
example.ETL:
  tasks:
    - EXTRACT
    - [TRANSFORM, queue2] # task-level
    - LOAD
  queue: queue1 # workflow-level
```

2022-07-07 12:22 UTC, CodePint commented
related:
https://github.com/ovh/celery-director/pull/134

2022-07-15 15:10 UTC, ncrocfer commented
Hi @henri42,

First of all thank you for this PR, it brings an interesting feature in Celery Director ! Unfortunately after a few tests I see it doesn't work for all the cases.

For instance everything is working for a simple ETL example:
![Capture d’écran 2022-07-15 à 16 49 07](https://user-images.githubusercontent.com/1552526/179250215-5c958d7e-3b9c-43b4-9fc9-892f3629e5b7.png)


But it doesn't work when a group of tasks is executed:
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/1552526/179248799-dc0641f5-6b23-4313-a49e-5e1ee952b0af.png">

I think you can update the builder to support it, but for me the syntax you choose is a bit confusing. The users will think it's a group of tasks, while it's just an array of 2 elements with the task and its queue.

The best is to provide another syntax, for instance using the `queue` key:

```yaml
example.ETL:
  tasks:
    - EXTRACT
    - TRANSFORM
    - LOAD
  queue:
    default: q1
    customs:
      EXTRACT: q2
```

Note this is just an example, I just wrote it quickly so I'm not sure about the final syntax ;) Also note if you do that you have to continue to support the current syntax, namely:

```yaml
  queue: q1
```

is the same as:

```yaml
  queue:
    default: q1
```

2022-07-15 15:10 UTC, ncrocfer requested changes
See https://github.com/ovh/celery-director/pull/155#issuecomment-1185639148

2022-07-18 13:30 UTC, henri42 commented
Thanks for your feedback !
Indeed this syntax can be confusing. I chose it to keep readability but it might be better with the syntax you suggested.
I will work on this new syntax and handle task-level queues for the tasks in groups.

2022-07-21 10:53 UTC, ncrocfer reviewed
I just checked and tested your PR and it works like a charm, thanks @henri42 :) Before merging it can you just amend your commit and sign it please (`git commit --amend -s`)?

2022-07-21 13:24 UTC, henri42 commented
Thanks !
That's done.

2022-07-21 15:05 UTC, ncrocfer approved these changes

2022-07-21 15:05 UTC, merged