feat(ui): auto refresh workflows list in director home page
ovh/celery-director pull request #88
Opened 2020-10-27 10:42 UTC by ismailrei

Adding an auto-refresh option on the director home page for refreshing the workflows and the status can be helpful for monitoring task status and flow

2020-10-30 16:40 UTC, ziirish approved these changes

2020-11-02 09:34 UTC, ncrocfer requested changes

2020-11-02 09:34 UTC, ncrocfer commented on director/settings.py
> +    "REFRESH_INTERVAL",
Isn't it `DIRECTOR_REFRESH_INTERVAL` ?

2020-11-02 10:28 UTC, ncrocfer approved these changes

2020-11-02 10:29 UTC, merged